version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 stella-server:app



  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web:web
